apiVersion: v2
name: csi-secrets-store-provider-azure
version: 1.0.2
appVersion: 1.0.1
kubeVersion: ">=1.16.0-0"
description: A Helm chart to install the Secrets Store CSI Driver and the Azure Keyvault Provider inside a Kubernetes cluster.
sources:
  - https://github.com/Azure/secrets-store-csi-driver-provider-azure
home: https://github.com/Azure/secrets-store-csi-driver-provider-azure
maintainers:
  - name: Anish Ramasekar
    email: anish.ramasekar@gmail.com
dependencies:
- name: secrets-store-csi-driver
  repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  version: 1.1.0-rc.0
  condition: secrets-store-csi-driver.install
