image:
  repository: mcr.microsoft.com/k8s/csi/secrets-store/provider-azure
  tag: 0.0.7
  pullPolicy: IfNotPresent

linux:
  nodeSelector: {}
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 50m
      memory: 100Mi

windows:
  nodeSelector: {}
  enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 200Mi

## Configuration values for the secrets-store-csi-driver dependency.
## ref: https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/charts/secrets-store-csi-driver/README.md
##
secrets-store-csi-driver:
  install: true
  linux:
    enabled: true
    kubeletRootDir: /var/lib/kubelet
  windows:
    enabled: false
    kubeletRootDir: C:\var\lib\kubelet
  logLevel:
    debug: true

## Install default service account
rbac:
  install: true
